---
title: "Testing"
author: "Alexandre Combeau"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#devtools::install_github("vrunge/dust0")
library(dust0)
#devtools::install_github("jchiquet/aricode")
library(aricode)
#devtools::install_github("gtromano/FOCuS")
library(FOCuS)
#install.packages("changepoint")
library(changepoint)
#devtools::install_github("vrunge/svpChange")
library(svpChange)
```

# Optimal Partitioning using R

```{r OP_R}
n <- 100
gap <- 0.5
chpts <- c(2, 5, 8, 13, 20)*n
data <- dataGenerator_1D(chpts = chpts,
                         parameters = c(0,gap,0,gap,0),
                         sdNoise = 1,
                         type = "gauss")
penalty <- 2 * log(length(data)) * dust0::sdDiff(data, "HALL")^2

# OP Algorithm
OP_R <- optimal_partitioning(data, penalty)

# Visualization
# par(bg = "white")
plot_segmentation(data, OP_R$changepoints, title = "Optimal Partitioning using R")
cp_metrics("OP_R", chpts, OP_R$changepoints, 5)
cat("Last cost R :", OP_R$costQ[length(OP_R$costQ)], "\n")
cat("OP_R$changepoints :", OP_R$changepoints, "\n")
cat("Expected          :", chpts, "\n")
```

# Optimal Partitioning using Rcpp

```{r OP_Rcpp}
n <- 100
gap <- 1
chpts <- c(2, 5, 8, 13, 20)*n
data <- dataGenerator_1D(chpts = chpts,
                         parameters = c(0,gap,0,gap,0),
                         sdNoise = 1,
                         type = "gauss")
penalty <- 2 * log(length(data)) * dust0::sdDiff(data, "HALL")^2

# OP Algorithm
OP_Rcpp <- optimal_partitioning_rcpp(data, penalty)

# Visualization
# par(bg = "white")
plot_segmentation(data, OP_Rcpp$changepoints, title = "Optimal Partitioning using Rcpp")
cp_metrics("OP_Rcpp", chpts, OP_Rcpp$changepoints, 10)
cat("Last cost Rcpp :", OP_Rcpp$costQ[length(OP_Rcpp$costQ)], "\n")
cat("OP_Rcpp$changepoints :", OP_Rcpp$changepoints, "\n")
cat("Expected             :", chpts, "\n")
```

# Time execution between OP (R) and OP (Rcpp)

```{r Exec_Time_OP}
n_vals <- 10^(seq(1, 2, length.out = 40))
gap <- 0.5
temps_R <- numeric(length(n_vals))
temps_Rcpp <- numeric(length(n_vals))
length_data <- integer(length(n_vals))

for (i in 1:length(n_vals))
{
  n <- n_vals[i]
  data <- dataGenerator_1D(chpts = c(2, 5, 8, 13, 20)*n,
                        parameters = c(0,gap,0,gap,0),
                        sdNoise = 1,
                        type = "gauss")
  length_data[i] <- length(data)
  print(length(data))
  penalty <- 2 * log(length(data)) * dust0::sdDiff(data, "HALL")^2
  
  # Execution time R
  t0 <- Sys.time()
  optimal_partitioning(data, penalty)
  t1 <- Sys.time()
  temps_R[i] <- as.numeric(difftime(t1, t0, units = "secs"))
  
  # Execution time C++
  t0 <- Sys.time()
  optimal_partitioning_rcpp(data, penalty)
  t1 <- Sys.time()
  temps_Rcpp[i] <- as.numeric(difftime(t1, t0, units = "secs"))
}

lm_R    <- lm(log(temps_R) ~ log(length_data))
lm_Rcpp <- lm(log(temps_Rcpp) ~ log(length_data))

plot(length_data, temps_R, type = "b", pch = 16, col = "red",
     log = "xy",
     xlab = "Length of data",
     ylab = "Time in seconds",
     main = "Execution Time for OP",
     ylim = range(c(temps_R, temps_Rcpp), finite = TRUE),
     xlim = range(length_data, finite = TRUE))
lines(length_data, temps_Rcpp, type = "b", pch = 17, col = "blue")

# Linear prediction for R code
y_pred_R <- exp(coef(lm_R)[1]) * length_data ^ coef(lm_R)[2]
lines(length_data, y_pred_R, col = "black", lty = 2, lwd = 2)

# Linear prediction for Rcpp code
y_pred_Rcpp <- exp(coef(lm_Rcpp)[1]) * length_data ^ coef(lm_Rcpp)[2]
lines(length_data, y_pred_Rcpp, col = "green", lty = 2, lwd = 2)

legend("topleft",
       legend = c(paste("R slope :", round(coef(lm_R)[2], 2)),
                  paste("Rcpp slope :", round(coef(lm_Rcpp)[2], 2))),
       col    = c("red", "blue"),
       pch    = c(16, 17),
       lty    = c(1, 1))
grid()
```

# Pruned Exact Linear Time using R

```{r PELT_R}
n <- 100
gap <- 0.5
chpts = c(2, 5, 8, 13, 20)*n
data <- dataGenerator_1D(chpts = chpts,
                      parameters = c(0,gap,0,gap,0),
                      sdNoise = 0.2,
                      type = "gauss")
penalty <- 2 * log(length(data))

# PELT Algorithm
PELT_R <- pelt(data, penalty)

# Visualization
plot_segmentation(data, PELT_R$changepoints, title = "PELT using R")
cp_metrics("PELT_R", chpts, PELT_R$changepoints, 5)
cat("Last cost R :", PELT_R$costQ[length(PELT_R$costQ)], "\n")
cat("PELT_R$changepoints :", PELT_R$changepoints, "\n")
cat("Expected            :", chpts, "\n")
```

# Pruned Exact Linear Time using Rcpp

```{r PELT_Rcpp}
n <- 1000
gap <- 0.2
chpts = floor(seq(0, n, length.out = floor(6*n/1000)+1))[-1]
parameters = rep(c(0,gap), ceiling(6*n/2000))
data <- dataGenerator_1D(chpts = chpts,
                         parameters = parameters[1:length(chpts)],
                         sdNoise = 0.2,
                         type = "gauss")
penalty <- 0.1 * log(length(data))

# PELT Algorithm
PELT_Rcpp <- pelt_rcpp(data, penalty)

# Visualization
plot_segmentation(data, PELT_Rcpp$changepoints, title = "PELT using Rcpp")
cp_metrics("PELT_Rcpp", chpts, PELT_Rcpp$changepoints, 5)
cat("Last cost PELT_Rcpp :", PELT_Rcpp$costQ[length(PELT_Rcpp$costQ)], "\n")
cat("PELT_Rcpp$changepoints :", PELT_Rcpp$changepoints, "\n")
cat("Expected               :", chpts, "\n")
```

# Time execution between PELT (R) and PELT (Rcpp)

```{r Exec_Time_PELT}
n_vals <- 10^(seq(1, 2, length.out = 40))
gap <- 0.5
temps_R <- numeric(length(n_vals))
temps_Rcpp <- numeric(length(n_vals))
length_data <- integer(length(n_vals))

for (i in 1:length(n_vals))
{
  n <- n_vals[i]
  data <- dataGenerator_1D(chpts = c(2, 5, 8, 13, 20)*n,
                        parameters = c(0,gap,0,gap,0),
                        sdNoise = 1,
                        type = "gauss")
  length_data[i] <- length(data)
  print(length(data))
  penalty <- 2 * log(length(data))
  
  # Execution time R
  t0 <- Sys.time()
  pelt(data, penalty)
  t1 <- Sys.time()
  temps_R[i] <- as.numeric(difftime(t1, t0, units = "secs"))
  
  # Execution time C++
  t0 <- Sys.time()
  pelt_rcpp(data, penalty)
  t1 <- Sys.time()
  temps_Rcpp[i] <- as.numeric(difftime(t1, t0, units = "secs"))
}

lm_R    <- lm(log(temps_R) ~ log(length_data))
lm_Rcpp <- lm(log(temps_Rcpp) ~ log(length_data))

plot(length_data, temps_R, type = "b", pch = 16, col = "red",
     log = "xy",
     xlab = "Length of data",
     ylab = "Time in seconds",
     main = "Execution Time for PELT",
     ylim = range(c(temps_R, temps_Rcpp), finite = TRUE),
     xlim = range(length_data, finite = TRUE))
lines(length_data, temps_Rcpp, type = "b", pch = 17, col = "blue")

# Linear prediction for R code
y_pred_R <- exp(coef(lm_R)[1]) * length_data ^ coef(lm_R)[2]
lines(length_data, y_pred_R, col = "black", lty = 2, lwd = 2)

# Linear prediction for Rcpp code
y_pred_Rcpp <- exp(coef(lm_Rcpp)[1]) * length_data ^ coef(lm_Rcpp)[2]
lines(length_data, y_pred_Rcpp, col = "green", lty = 2, lwd = 2)

legend("topleft",
       legend = c(paste("R slope :", round(coef(lm_R)[2], 2)),
                  paste("Rcpp slope :", round(coef(lm_Rcpp)[2], 2))),
       col    = c("red", "blue"),
       pch    = c(16, 17),
       lty    = c(1, 1))
grid()
```

# Smallest Valid Partitioning

```{r svp}
n <- 1000
gap <- 1

chpts0 <- c(0.1, 0.3, 0.4, 0.45, 0.55, 0.7, 0.75, 0.95, 1) * n
data <- dataGenerator_1D(chpts = chpts0,
                         parameters = c(0, gap, 0, gap, 0, gap, 0, gap, 0),
                         sdNoise    = 1.5)
gamma <- 10
plot(data)

# SVP Algorithm
res_SVP <- SVP(data, gamma, test="gaussian_mean", T)
cat("res_SVP$changepoints     :", res_SVP$changepoints, "\n")
Focus <- FOCuS::FOCuS(data[1:250],gamma)$changepoint
cat("Focus :", Focus, "\n")
argmax_OP <- valid_OP_argmax(data[1:250], gamma)$argmax
cat("argmax_OP :", argmax_OP, "\n")
chpts <- c(0, res_SVP$changepoints)
res_FOCUS <- c()
valid_OP_argmax_i <- c()
for (i in seq_len(length(chpts) - 2))
{
  segment_start <- chpts[i] + 1
  segment_end   <- chpts[i + 2]
  cat("[", segment_start, ";", segment_end, "]\n")
  res_FOCUS[i]  <- FOCuS::FOCuS(data[segment_start:segment_end],gamma)$changepoint
  valid_OP_argmax_i[i] <- valid_OP_argmax(data[segment_start:segment_end],gamma)$argmax
}

diff(res_SVP$changepoints)
# Visualization
plot_segmentation(data, res_SVP$changepoints, title = "SVP")
cat("res_SVP$changepoints     :", res_SVP$changepoints, "\n")
cat("res_FOCUS$changepoints   :", c(res_FOCUS, n), "\n")
cat("valid_OP_argmax_i$argmax :", c(valid_OP_argmax_i, n), "\n")
cat("Expected                 :", chpts0, "\n")
```


```{r SVP_execution_time2}
# Packages nécessaires
library(future.apply)

# ----------------------
# Paramètres
# ----------------------
start <- 10000
end   <- 20000
n_vals <- round(10^(seq(log10(start), log10(end), length.out = 50)))

bench_SVP <- function(n)
{
  # Constantes locales (important sous Windows !)
  gap   <- 0.5
  gamma <- 18
  
  # Changepoints relatifs
  chpts <- c(0.1, 0.3, 0.4, 0.45, 0.55, 0.7, 0.75, 0.95, 1) * n
  data <- dataGenerator_1D(
    chpts      = chpts,
    parameters = c(0, gap, 0, gap, 0, gap, 0, gap, 0),
    sdNoise    = 1.5
  )
  
  # Chrono avec pruning
  SVP_true  <- system.time(SVP(data, gamma, test="gaussian_mean", prune_if_unvalid = TRUE))[["elapsed"]]
  
  # Chrono sans pruning
  SVP_false <- system.time(SVP(data, gamma, test="gaussian_mean", prune_if_unvalid = FALSE))[["elapsed"]]
  
  list(n = length(data), SVP_true = SVP_true, SVP_false = SVP_false)
}

bench_PELT <- function(n)
{
  # Constantes locales (important sous Windows !)
  penalty <- 2.2 * log(n)
  
  # Changepoints relatifs
  chpts <- c(0.1,0.3,0.4,0.45,0.55,0.7,0.75,0.95,1) * n
  data <- dataGenerator_1D(
    chpts      = chpts,
    parameters = c(0,gap,0,gap,0,gap,0,gap,0),
    sdNoise    = 1.5
  )

  # Chrono avec pruning
  SVP_true <- system.time(pelt(data, penalty))[["elapsed"]]

  # Chrono sans pruning
  SVP_false <- system.time(pelt(data, penalty))[["elapsed"]]

  list(n = length(data), SVP_true = SVP_true, SVP_false = SVP_false)
}

# ----------------------
# Exécution en parallèle
# ----------------------
plan(multisession, workers = parallel::detectCores() - 1)

t0 <- Sys.time()
res <- future_lapply(n_vals, bench_PELT, future.seed = TRUE)
t1 <- Sys.time()
cat("temps ecoule :", as.numeric(difftime(t1, t0, units = "secs")))


# Assemblage en data.frame
df <- do.call(rbind, lapply(res, as.data.frame))
print(df)

# ----------------------
# Régressions log-log
# ----------------------

lm_SVP_true  <- lm(log(df$SVP_true)  ~ log(df$n))
lm_SVP_false <- lm(log(df$SVP_false) ~ log(df$n))

# ----------------------
# Plot comparatif
# ----------------------

plot(df$n, df$SVP_true, type = "b", pch = 16, col = "red",
     log = "xy",
     xlab = "Length of data (n)",
     ylab = "Time (s)",
     main = "SVP: Pruning ON vs Pruning OFF",
     ylim = range(c(df$SVP_true, df$SVP_false), finite = TRUE),
     xlim = range(df$n, finite = TRUE))
lines(df$n, df$SVP_false, type = "b", pch = 17, col = "blue")

# Linear prediction for SVP Pruning
y_pred_SVP_true <- exp(coef(lm_SVP_true)[1]) * df$n ^ coef(lm_SVP_true)[2]
lines(df$n, y_pred_SVP_true, col = "red", lty = 2, lwd = 2)

# Linear prediction for SVP NO Pruning
y_pred_SVP_false <- exp(coef(lm_SVP_false)[1]) * df$n ^ coef(lm_SVP_false)[2]
lines(df$n, y_pred_SVP_false, col = "blue", lty = 2, lwd = 2)

legend("topleft",
       legend = c(paste("pelt :", round(coef(lm_SVP_true)[2], 2)),
                  paste("pelt_rcpp :", round(coef(lm_SVP_false)[2], 2))),
       col    = c("red", "blue"),
       pch    = c(16, 17),
       lty    = c(1, 1))
grid()
```


```{r SVP}
nb_add_data <- 20
temps_R <- numeric(nb_add_data)
length_data <- integer(nb_add_data)
data <- c()
gamma <- 4
for (i in 1:nb_add_data)
{
  data <- c(data, rnorm(50, 1, 1), rnorm(50, 0, 1), rnorm(50, 1, 1), rnorm(50, 0, 1))
  print(i)
  length_data[i] <- 200*i
  
  # Execution time
  t0 <- Sys.time()
  local <- smallest_valid_partitioning_rcpp(data, gamma, valid_FOCUS, T, F)
  t1 <- Sys.time()
  temps_R[i] <- as.numeric(difftime(t1, t0, units = "secs"))
  cat("number of chpts :", length(local$changepoints), "\n")
}

lm_R <- lm(log(temps_R) ~ log(length_data))

plot(length_data, temps_R, type = "b", pch = 16, col = "red",
     log = "xy",
     xlab = "Length of data",
     ylab = "Time in seconds",
     main = "Execution Time : SVP FOCuS",
     ylim = range(temps_R, finite = TRUE),
     xlim = range(length_data, finite = TRUE))

# Linear prediction for R code
y_pred_R <- exp(coef(lm_R)[1]) * length_data ^ coef(lm_R)[2]
lines(length_data, y_pred_R, col = "black", lty = 2, lwd = 2)

legend("topleft",
       legend = c(paste("Slope :", round(coef(lm_R)[2], 2))),
       col    = "red",
       pch    = c(16, 17),
       lty    = c(1, 1))
grid()
```

```{r SVP_complexity}
n <- 10^(seq(1, 3, length.out = 100))
temps_SVP <- numeric(length(n))
gamma <- 12
for (i in 1:length(n))
{
  data <- c(rnorm(n[i]/2, 5, 1), rnorm(n[i]/2, 0, 1))
  print(i)
  
  # Execution time
  t0 <- Sys.time()
  local <- SVP(data, gamma, test = "gaussian_mean", prune_if_unvalid = T)
  #local <- smallest_valid_partitioning_rcpp(data, gamma, valid_FOCUS, T, T)
  t1 <- Sys.time()
  temps_SVP[i] <- as.numeric(difftime(t1, t0, units = "secs"))
  cat("number of chpts :", length(local$changepoints), "\n")
}

length_data <- n

lm_SVP <- lm(log(temps_SVP) ~ log(length_data))

plot(length_data, temps_SVP, type = "b", pch = 16, col = "red",
     log = "xy",
     xlab = "Length of data",
     ylab = "Time in seconds",
     main = "Execution Time : SVP FOCuS",
     ylim = range(temps_SVP, finite = TRUE),
     xlim = range(length_data, finite = TRUE))

# Linear prediction for R code
y_pred_SVP <- exp(coef(lm_SVP)[1]) * length_data ^ coef(lm_SVP)[2]
lines(length_data, y_pred_SVP, col = "black", lty = 2, lwd = 2)

legend("topleft",
       legend = c(paste("Slope :", round(coef(lm_SVP)[2], 2))),
       col    = "red",
       pch    = c(16, 17),
       lty    = c(1, 1))
grid()
```


```{r SVP_valid_FOCUS}
n <- 10000
gap <- 10
chpts = c(0.1,0.3,0.4,0.45,0.55,0.7,0.75,0.95,1)*n
data <- dataGenerator_1D(chpts = chpts,
                         parameters = c(0,gap,0,gap,0,gap,0,gap,0),
                         sdNoise = 1.5,
                         type = "gauss")
plot(data)
gamma <- 23
res1 <- SVP(data, gamma, test = "gaussian_mean", prune_if_unvalid = T)
res2 <- pelt_rcpp(data, gamma)
cat("Obtained :", res1$changepoints, "\n")
cat("Expected :", chpts, "\n")
abline(v = res1$changepoints, col = "red")
cp_est <- res1$changepoints
#plot_segmentation(data, res1$changepoints, title = "Segmentation Plot")
cp_metrics(chpts, res1$changepoints, tol = 10)
cp_metrics(chpts, res2$changepoints, tol = 10)
```

# SVP_PELT = PELT ?

```{r SVP_PELT_equal_PELT}
gap <- 2
n <- 500
data <- dataGenerator_1D(chpts = c(0.1,0.3,0.4,0.45,0.55,0.7,0.75,0.95,1)*n,
                         parameters = c(0,gap,0,gap,0,gap,0,gap,0),
                         sdNoise = 1.5)
penalty <- 2 * log(length(data)) * dust0::sdDiff(data, method = "HALL")^2
pen <- 30

# Expected
plot(data, type = 'b')
abline(v = c(0.1,0.3,0.4,0.45,0.55,0.7,0.75,0.95,1)*n, col = 2, lwd = 3)

# PELT
resPELT <- pelt_rcpp(data, penalty)
plot_segmentation(data, resPELT$changepoints,
                  title = paste("PELT, penalty =", round(penalty, 2)))

# SVP_OP
SVP_OP <- smallest_valid_partitioning(data, penalty)
cpts <- SVP_OP$changepoints
plot_segmentation(data, SVP_OP$changepoints,
                  title = paste("SVP_valid_OP, gamma =", round(penalty, 2)))

plot(resPELT$nb)
plot(SVP_OP$nb)
res_focus <- smallest_valid_partitioning(data, gamma = pen, test = valid_FOCUS)
plot(res_focus$nb)
resRange <- smallest_valid_partitioning(data, gamma = 8, test = valid_RANGE)
plot(resRange$nb)
resRange_slack <- smallest_valid_partitioning(data, gamma = 4, test = valid_RANGE_SLACK)
plot(resRange_slack$nb)
```

# Comparison of segmentations using ARI

```{r ARI_valid_FOCuS}
n <- 1000
gap <- 2
chpts = c(0.1,0.3,0.4,0.45,0.55,0.7,0.75,0.95,1)*n
data <- dataGenerator_1D(chpts = chpts,
                         parameters = c(0,gap,0,gap,0,gap,0,gap,0),
                         sdNoise = 1.5)
gamma <- 25

res_1 <- smallest_valid_partitioning(data, gamma, test = valid_FOCUS)

res_1$changepoints

plot_segmentation(data, res_1$changepoints,
                  title = paste("valid_FOCuS, gamma =", round(gamma, 2)))

cpts <- c(0, res_1$changepoints)
mean_values <- integer(length(cpts) - 1)
for (i in 1:(length(cpts) - 1))
{
  mean_values[i] <- mean(data[(cpts[i] + 1):cpts[i + 1]])
}

times <- cpts[2]
for (i in 2:length(mean_values))
{
  times[i] <- cpts[i+1] - cpts[i]
}
partition_SVP_FOCUS <- rep(mean_values, times = times)

plot_segmentation(data, chpts, title = "Expected Segmentation")

cpts <- c(0,chpts)
mean_values <- integer(length(cpts) - 1)
for (i in 1:(length(cpts) - 1))
{
  mean_values[i] <- mean(data[(cpts[i] + 1):cpts[i + 1]])
}

times <- cpts[2]
for (i in 2:length(mean_values))
{
  times[i] <- cpts[i+1] - cpts[i]
}
partition_expected <- rep(mean_values, times = times)

ARI(partition_SVP_FOCUS, partition_expected)
```

```{r Exec_Time_PELT}
n_vals <- 10^(seq(1, 1.5, length.out = 3))
gap <- 0.5
temps_R <- numeric(length(n_vals))
temps_Rcpp <- numeric(length(n_vals))
length_data <- integer(length(n_vals))

for (i in 1:length(n_vals))
{
  n <- n_vals[i]
  data <- dataGenerator_1D(chpts = c(2, 5, 8, 13, 20)*n,
                        parameters = c(0,gap,0,gap,0),
                        sdNoise = 1,
                        type = "gauss")
  length_data[i] <- length(data)
  print(length(data))
  gamma <- 10
  
  # Execution time R
  t0 <- Sys.time()
  smallest_valid_partitioning(data, gamma, test = valid_FOCUS)
  t1 <- Sys.time()
  temps_R[i] <- as.numeric(difftime(t1, t0, units = "secs"))
  
  # Execution time C++
  t0 <- Sys.time()
  smallest_valid_partitioning(data, gamma, test = valid_RANGE)
  t1 <- Sys.time()
  temps_Rcpp[i] <- as.numeric(difftime(t1, t0, units = "secs"))
}

lm_R    <- lm(log(temps_R) ~ log(length_data))
lm_Rcpp <- lm(log(temps_Rcpp) ~ log(length_data))

plot(length_data, temps_R, type = "b", pch = 16, col = "red",
     log = "xy",
     xlab = "Length of data",
     ylab = "Time in seconds",
     main = "Execution Time",
     ylim = range(c(temps_R, temps_Rcpp), finite = TRUE),
     xlim = range(length_data, finite = TRUE))
lines(length_data, temps_Rcpp, type = "b", pch = 17, col = "blue")

# Linear prediction for R code
y_pred_R <- exp(coef(lm_R)[1]) * length_data ^ coef(lm_R)[2]
lines(length_data, y_pred_R, col = "black", lty = 2, lwd = 2)

# Linear prediction for Rcpp code
y_pred_Rcpp <- exp(coef(lm_Rcpp)[1]) * length_data ^ coef(lm_Rcpp)[2]
lines(length_data, y_pred_Rcpp, col = "green", lty = 2, lwd = 2)

legend("topleft",
       legend = c(paste("SVP_FOCuS, gamma =", gamma,
                        "; slope =", round(coef(lm_R)[2],2)),
                  paste("SVP_RANGE, gamma =", gamma,
                        "; slope =", round(coef(lm_Rcpp)[2],2))),
       col    = c("red", "blue"),
       pch    = c(16, 17),
       lty    = c(1, 1))
grid()
```

```{r testthat1}
library(testthat)

test_that("SVP with valid_FOCUS and SVP_focus produce similar results", {
  #set.seed(42)
  #n <- 500
  #gap <- 2
  #chpts = c(0.1,0.3,0.4,0.45,0.55,0.7,0.75,0.95,1)*n
  #data <- dataGenerator_1D(chpts = chpts,
  #                       parameters = c(0,gap,0,gap,0,gap,0,gap,0),
  #                       sdNoise = 1.5)
  #gamma <- 15

  # Use valid_FOCUS as the test function
  svp_1 <- smallest_valid_partitioning(data, gamma, test = valid_FOCUS)
  svp_2 <- smallest_valid_partitioning_rcpp(data, gamma, test = valid_FOCUS)
  
  # Their changepoints should be similar
  expect_equal(svp_1$changepoints, svp_2$changepoints, tolerance = 0)

  # Their costQ vectors should be nearly identical
  expect_equal(svp_1$costQ, svp_2$costQ, tolerance = 1e-6)
  
  # Their $nb should be similar
  #expect_equal(svp_1$nb, svp_2$nb, tolerance = 0)
  
  # Their $R should be similar
  expect_equal(svp_1$R, svp_2$R, tolerance = 1e-6)
})
```

```{r Exec_Time_OP}
n_vals <- 10^(seq(1, 3, length.out = 40))
gap <- 0.5
temps_R <- numeric(length(n_vals))
temps_Rcpp <- numeric(length(n_vals))
length_data <- integer(length(n_vals))

for (i in 1:length(n_vals))
{
  n <- n_vals[i]
  data <- dataGenerator_1D(chpts = c(2, 5, 8, 13, 20)*n,
                        parameters = c(0,gap,0,gap,0),
                        sdNoise = 1,
                        type = "gauss")
  length_data[i] <- length(data)
  print(length(data))
  penalty <- 2 * log(length(data)) * dust0::sdDiff(data, "HALL")^2
  gamma <- 10
  
  # Execution time R
  t0 <- Sys.time()
  SVP(data, gamma, test = "gaussian_mean")
  t1 <- Sys.time()
  temps_R[i] <- as.numeric(difftime(t1, t0, units = "secs"))
  
  # Execution time C++
  t0 <- Sys.time()
  pelt_rcpp(data, penalty)
  t1 <- Sys.time()
  temps_Rcpp[i] <- as.numeric(difftime(t1, t0, units = "secs"))
}

lm_R    <- lm(log(temps_R) ~ log(length_data))
lm_Rcpp <- lm(log(temps_Rcpp) ~ log(length_data))

plot(length_data, temps_R, type = "b", pch = 16, col = "red",
     log = "xy",
     xlab = "Length of data",
     ylab = "Time in seconds",
     main = "Execution Time SVP / OP",
     ylim = range(c(temps_R, temps_Rcpp), finite = TRUE),
     xlim = range(length_data, finite = TRUE))
lines(length_data, temps_Rcpp, type = "b", pch = 17, col = "blue")

# Linear prediction for R code
y_pred_R <- exp(coef(lm_R)[1]) * length_data ^ coef(lm_R)[2]
lines(length_data, y_pred_R, col = "black", lty = 2, lwd = 2)

# Linear prediction for Rcpp code
y_pred_Rcpp <- exp(coef(lm_Rcpp)[1]) * length_data ^ coef(lm_Rcpp)[2]
lines(length_data, y_pred_Rcpp, col = "green", lty = 2, lwd = 2)

legend("topleft",
       legend = c(paste("SVP slope :", round(coef(lm_R)[2], 2)),
                  paste("OP_PELT slope :", round(coef(lm_Rcpp)[2], 2))),
       col    = c("red", "blue"),
       pch    = c(16, 17),
       lty    = c(1, 1))
grid()
```


