// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// smallest_valid_partitioning_rcpp
List smallest_valid_partitioning_rcpp(NumericVector data, double gamma, Function test, bool all_full_validity);
RcppExport SEXP _changepoints_smallest_valid_partitioning_rcpp(SEXP dataSEXP, SEXP gammaSEXP, SEXP testSEXP, SEXP all_full_validitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< Function >::type test(testSEXP);
    Rcpp::traits::input_parameter< bool >::type all_full_validity(all_full_validitySEXP);
    rcpp_result_gen = Rcpp::wrap(smallest_valid_partitioning_rcpp(data, gamma, test, all_full_validity));
    return rcpp_result_gen;
END_RCPP
}
// smallest_valid_partitioning_rcpp_seq
List smallest_valid_partitioning_rcpp_seq(NumericVector data, double gamma, std::string test, bool all_full_validity);
RcppExport SEXP _changepoints_smallest_valid_partitioning_rcpp_seq(SEXP dataSEXP, SEXP gammaSEXP, SEXP testSEXP, SEXP all_full_validitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< std::string >::type test(testSEXP);
    Rcpp::traits::input_parameter< bool >::type all_full_validity(all_full_validitySEXP);
    rcpp_result_gen = Rcpp::wrap(smallest_valid_partitioning_rcpp_seq(data, gamma, test, all_full_validity));
    return rcpp_result_gen;
END_RCPP
}
// optimal_partitioning_rcpp
List optimal_partitioning_rcpp(std::vector<double> data, double penalty);
RcppExport SEXP _changepoints_optimal_partitioning_rcpp(SEXP dataSEXP, SEXP penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(optimal_partitioning_rcpp(data, penalty));
    return rcpp_result_gen;
END_RCPP
}
// pelt_rcpp
List pelt_rcpp(std::vector<double> data, double penalty);
RcppExport SEXP _changepoints_pelt_rcpp(SEXP dataSEXP, SEXP penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(pelt_rcpp(data, penalty));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_changepoints_smallest_valid_partitioning_rcpp", (DL_FUNC) &_changepoints_smallest_valid_partitioning_rcpp, 4},
    {"_changepoints_smallest_valid_partitioning_rcpp_seq", (DL_FUNC) &_changepoints_smallest_valid_partitioning_rcpp_seq, 4},
    {"_changepoints_optimal_partitioning_rcpp", (DL_FUNC) &_changepoints_optimal_partitioning_rcpp, 2},
    {"_changepoints_pelt_rcpp", (DL_FUNC) &_changepoints_pelt_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_changepoints(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
