// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SN
List SN(std::vector<double> data, int Kmax);
RcppExport SEXP _changepoints_SN(SEXP dataSEXP, SEXP KmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type Kmax(KmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(SN(data, Kmax));
    return rcpp_result_gen;
END_RCPP
}
// SVP
List SVP(std::vector<double> data, double gamma, std::string test, bool prune_if_unvalid);
RcppExport SEXP _changepoints_SVP(SEXP dataSEXP, SEXP gammaSEXP, SEXP testSEXP, SEXP prune_if_unvalidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< std::string >::type test(testSEXP);
    Rcpp::traits::input_parameter< bool >::type prune_if_unvalid(prune_if_unvalidSEXP);
    rcpp_result_gen = Rcpp::wrap(SVP(data, gamma, test, prune_if_unvalid));
    return rcpp_result_gen;
END_RCPP
}
// svp0
List svp0(std::vector<double> data, double gamma, Function test, bool prune_if_unvalid, bool prune_if_PELT);
RcppExport SEXP _changepoints_svp0(SEXP dataSEXP, SEXP gammaSEXP, SEXP testSEXP, SEXP prune_if_unvalidSEXP, SEXP prune_if_PELTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< Function >::type test(testSEXP);
    Rcpp::traits::input_parameter< bool >::type prune_if_unvalid(prune_if_unvalidSEXP);
    Rcpp::traits::input_parameter< bool >::type prune_if_PELT(prune_if_PELTSEXP);
    rcpp_result_gen = Rcpp::wrap(svp0(data, gamma, test, prune_if_unvalid, prune_if_PELT));
    return rcpp_result_gen;
END_RCPP
}
// optimal_partitioning_rcpp
List optimal_partitioning_rcpp(std::vector<double> data, double penalty);
RcppExport SEXP _changepoints_optimal_partitioning_rcpp(SEXP dataSEXP, SEXP penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(optimal_partitioning_rcpp(data, penalty));
    return rcpp_result_gen;
END_RCPP
}
// pelt_rcpp
List pelt_rcpp(std::vector<double> data, double penalty);
RcppExport SEXP _changepoints_pelt_rcpp(SEXP dataSEXP, SEXP penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(pelt_rcpp(data, penalty));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_changepoints_SN", (DL_FUNC) &_changepoints_SN, 2},
    {"_changepoints_SVP", (DL_FUNC) &_changepoints_SVP, 4},
    {"_changepoints_svp0", (DL_FUNC) &_changepoints_svp0, 5},
    {"_changepoints_optimal_partitioning_rcpp", (DL_FUNC) &_changepoints_optimal_partitioning_rcpp, 2},
    {"_changepoints_pelt_rcpp", (DL_FUNC) &_changepoints_pelt_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_changepoints(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
