# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Smallest Valid Partitioning with Validation and Pruning using Rcpp
#' 
#' @title Smallest Valid Partitioning with Validation and Pruning
#' @description This function implements a dynamic programming approach to segment a univariate signal into the smallest number of valid segments, according to a user-defined validation function. Each segment must pass a validity test (e.g., based on variance, range, etc.). The algorithm minimizes a quadratic cost subject to this constraint.
#' 
#' @param data A numeric vector representing the univariate signal to be segmented.
#' @param gamma A numeric value used as a threshold in the validation function and as a penalty for each segment.
#' @param test A function of the form `function(data, gamma)` returning TRUE if the segment is valid. Default is `valid_OP`.
#' @param all_full_validity Logical. If TRUE (default), the algorithm applies *segment-wise validation*:
#' at each time step, it tests whether the candidate segment \code{data[(s+1):t]} is valid using the
#' user-defined function \code{test}. If the segment fails the test, the candidate \code{s} is removed
#' (pruned) from the set of possible changepoints. This accelerates computation by avoiding invalid
#' segment extensions. If FALSE, the algorithm skips this validation and considers all candidate
#' segments without checking their validity (which can be faster but may return invalid segments).
#' 
#' @return A list with the following components :
#' \describe{
#'   \item{changepoints}{Integer vector indicating the ending index of each segment (i.e., positions of changepoints).}
#'   \item{nb}{Integer vector of length \code{length(data)}. At each position \code{t}, it records the number of candidates tested.}
#'   \item{costQ}{Numeric vector of length \code{length(data)}. Quadratic cost value at each time step.}
#'   \item{R}{A matrix of dimension \code{(length(data)+1) x 3} containing, for each time step :
#'     \describe{
#'       \item{Q}{cumulative cost}
#'       \item{K}{number of segments}
#'       \item{s}{previous changepoint}
#'     }
#'   }
#' }
#' 
#' @export
smallest_valid_partitioning_rcpp <- function(data, gamma, test, all_full_validity = TRUE) {
    .Call(`_changepoints_smallest_valid_partitioning_rcpp`, data, gamma, test, all_full_validity)
}

smallest_valid_partitioning_rcpp_seq <- function(data, gamma, test, all_full_validity = TRUE) {
    .Call(`_changepoints_smallest_valid_partitioning_rcpp_seq`, data, gamma, test, all_full_validity)
}

#' Optimal Partitioning algorithm using Rcpp
#' 
#' @title Optimal Partitioning
#' @description This function implements the OP algorithm of a given vector `data` with a given penalty term.
#' It finds the optimal changepoints that minimize the cost function using dynamic programming.
#' 
#' @param data A numeric vector representing the data to segment.
#' @param penalty A double value representing the penalty term for adding a new segment.
#' 
#' @return A list with (1) the `\code{changepoints}` elements, (2) a vector `\code{nb}` saving the number of non-pruned elements at each iteration, (3) a vector `\code{lastIndexSet}` containing the non-pruned indices at the end of the algo and (4) a vector `\code{costQ}` saving the optimal cost at each time step.
#' 
#' @examples
#' n <- 1000
#' data <- rep(c(0, 5, 2.5, 7), each = n) + rnorm(4 * n)
#' penalty <- 2 * log(length(data))
#' OP_Rcpp <- optimal_partitioning_rcpp(data, penalty)
#' plot_segmentation(data, OP_Rcpp$changepoints, title = "OP Segmentation")
#' 
#' @export
optimal_partitioning_rcpp <- function(data, penalty) {
    .Call(`_changepoints_optimal_partitioning_rcpp`, data, penalty)
}

#' Optimal Partitioning algorithm using PELT
#' 
#' @title Optimal Partitioning using PELT
#' @description This function implements the OP algorithm using PELT of a given vector `data` with a given penalty term.
#' It finds the optimal changepoints that minimize the cost function using dynamic programming.
#' 
#' @param data A numeric vector representing the data to segment.
#' @param penalty A double value representing the penalty term for adding a new segment.
#' 
#' @return A list with
#' (1) the changepoint elements (each last index of each segment in \code{changepoints}),
#' (2) a vector \code{nb} saving the number of non-pruned elements at each iteration,
#' (3) a vector \code{lastIndexSet} containing the non-pruned indices at the end of the algorithm,
#' (4) a vector \code{costQ} saving the optimal cost at each time step.
#' 
#' @examples
#' n <- 1000
#' data <- rep(c(0, 5, 2.5, 7), each = n) + rnorm(4 * n)
#' penalty <- 2 * log(length(data))
#' PELT_Rcpp <- pelt_rcpp(data, penalty)
#' plot_segmentation(data, PELT_Rcpp$changepoints, title = "PELT Segmentation")
#' 
#' @export
pelt_rcpp <- function(data, penalty) {
    .Call(`_changepoints_pelt_rcpp`, data, penalty)
}

