# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Optimal Partitioning Method using C++
#' 
#' @title Optimal Partitioning Method
#' @description This function computes the optimal partitioning of a given vector x with a given penalty term beta. It finds the optimal changepoints that minimize the cost function using dynamic programming.
#' @param x A numeric vector representing the data to segment.
#' @param beta A double value representing the penalty term for adding a new segment.
#' @return A list with (1) the changepoint elements (each last index of each segment in \code{changepoints}), (2) a vector `\code{nb} saving the number of non-pruned elements at each iteration, (3) a vector \code{lastIndexSet} containing the non-pruned indices at the end of the algo and (4) a vector \code{costQ} saving the optimal cost at each time step.
#' @export
rcpp_optimal_partitioning <- function(x, beta) {
    .Call(`_changepoints_rcpp_optimal_partitioning`, x, beta)
}

#' PELT Method using C++
#' 
#' @title PELT Method
#' @description This function implements the PELT (Pruned Exact Linear Time) method in Rcpp.
#' @param x A numeric vector representing the data to segment.
#' @param penalty A double value representing the penalty term for adding a new segment.
#' @param minseglen The minimum length of the segment.
#' @return A list with (1) the changepoint elements (each last index of each segment in \code{changepoints}), (2) a vector `\code{nb} saving the number of non-pruned elements at each iteration, (3) a vector \code{lastIndexSet} containing the non-pruned indices at the end of the algo and (4) a vector \code{costQ} saving the optimal cost at each time step.
#' @export
rcpp_pelt <- function(x, penalty, minseglen = 1L) {
    .Call(`_changepoints_rcpp_pelt`, x, penalty, minseglen)
}

